# <font color='blue'> 1. Tokenization - Getting your text ready </font>

## <font> Tokenization </font>

- how to represent words in a way that a computer can process them. 
- with view to later training a neural network that can understand their meaning

## <font> Word(letter) : Number(Encoding), Sequence </font>


- the word for example "listen" is represented by number using an encoding scheme (ASCII CODE... etc..)
- But the order of number is important
 
`listen = [76, 73, 83, 84, 69, 78]`

`silent = [83, 73, 76, 69, 78, 84]`

- this bunch of numbers can then represent the word listen but word silent has the same letters, and thus the same numbers, just in a different order.
- It makes it hard for us to understand sentiment of a word just by the letters in it

## <font > Sentence : Tokenization </font>

- So it might be easier, instead of encoding letters to encode words. 
- Consider the sentence I love my dog.
- what would happen if we start encoding the words in this sentence instead of letters in each word?

`sentence1 = {'I':1, "love":2, "my":3, "dog":4}`

`sentence2 = {'I':1, "love":2, "my":3, "cat":5}`

- two sentences are already show some form of similarity between them.
- And it's a similarity you would expect, because they're both about loving a pet.
- Given this method of encoding sentences into number, now let's kate a look at some code to archieve this for us. : This process, is called tokenization

## <font> Tensorflow Tools : Tokenizer </font>

- You will see how words can be tokenized and tools in tensorflow that handle that tokenization for you

In [4]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.text import Tokenizer

In [5]:
sentence = ['I love my dog',
            'I love my cat']

tokenizer = Tokenizer(num_words = 100)
tokenizer.fit_on_texts(sentence)
word_index = tokenizer.word_index
print(word_index)

{'i': 1, 'love': 2, 'my': 3, 'dog': 4, 'cat': 5}


In [6]:
sentence.append('you love my dog!')

tokenizer = Tokenizer(num_words = 100)
tokenizer.fit_on_texts(sentence)
word_index = tokenizer.word_index
print(word_index)

{'love': 1, 'my': 2, 'i': 3, 'dog': 4, 'cat': 5, 'you': 6}


- Now that your words are represented by numbers like this, 
- you'll next need to represent your sentences by sequences of numbers in the correct order
- You'll then have data ready for processing by a neural network to understand or maybe oeven generate new text

## Sequencing - Turning sentences into data

- creating sequences of numbers from your sentences
- And using tools to process them to make them ready for teaching neural network

- Last time, we saw how to take a set of sentences and use the tokenizer to turn the words into numberic tokens.
- Let's build on that now by also seeing how the senteces containing these words.
- Can be turned into sequences of numbers.
- We'll add another sentence to our set of texts, and I'm doing this because the existing sentences all have four words
- and it's important to see how to manage sentences, or sequences, of different lengths
- The tokenizer supports a method called texts to sequences which performs most of the work for you.
- It creates sequences of tokens representing each sentence. 

In [9]:
sentence = ['I love my dog',
            'I love my cat',
            'You love my dog!',
            'Do you think my dog is amazing?']

tokenizer = Tokenizer(num_words=100)
tokenizer.fit_on_texts(sentence)
word_index = tokenizer.word_index
word_index

{'my': 1,
 'love': 2,
 'dog': 3,
 'i': 4,
 'you': 5,
 'cat': 6,
 'do': 7,
 'think': 8,
 'is': 9,
 'amazing': 10}

In [10]:
sequences = tokenizer.texts_to_sequences(sentence)
sequences

[[4, 2, 1, 3], [4, 2, 1, 6], [5, 2, 1, 3], [7, 5, 8, 1, 3, 9, 10]]

- word_index : you can see the list of word-value pairs for the tokens.
- sequences : you can see that the sequences that texts to sequences has returned.
- We have a few new words such as amazing, think is and do, 
    - that's why this index looks a little different than before.
    - And now, we have the sequences. 

- 4,2,1,3: tokens for I, love, my, dog
- 4,2,1,6: tokens for I, love, my, cat 

## Basic tokenization done

- this is all very well for getting data ready for training a neural network, 
- but what happens when that neural network needs to classify texts, but there are words in the text that it has never seen before?
- This can confuse the tokenizer, so we'll look at how to handle that next.

In [11]:
test_data = ['i really love my dog',
             'my dog loves my manatee']

test_seq = tokenizer.texts_to_sequences(test_data)
test_seq

[[4, 2, 1, 3], [1, 3, 1]]

In [12]:
tokenizer = Tokenizer(num_words=100, oov_token="<OOV>")
tokenizer.fit_on_texts(sentence)
word_index = tokenizer.word_index
word_index

{'<OOV>': 1,
 'my': 2,
 'love': 3,
 'dog': 4,
 'i': 5,
 'you': 6,
 'cat': 7,
 'do': 8,
 'think': 9,
 'is': 10,
 'amazing': 11}

In [13]:
test_seq = tokenizer.texts_to_sequences(test_data)
test_seq

[[5, 1, 3, 2, 4], [2, 4, 1, 2, 1]]

In [16]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

padded = pad_sequences(sequences)
padded

array([[ 0,  0,  0,  4,  2,  1,  3],
       [ 0,  0,  0,  4,  2,  1,  6],
       [ 0,  0,  0,  5,  2,  1,  3],
       [ 7,  5,  8,  1,  3,  9, 10]], dtype=int32)

In [17]:
padded = pad_sequences(sequences, padding='post')
padded

array([[ 4,  2,  1,  3,  0,  0,  0],
       [ 4,  2,  1,  6,  0,  0,  0],
       [ 5,  2,  1,  3,  0,  0,  0],
       [ 7,  5,  8,  1,  3,  9, 10]], dtype=int32)

In [18]:
padded = pad_sequences(sequences, padding='post', maxlen=5)
padded

array([[ 4,  2,  1,  3,  0],
       [ 4,  2,  1,  6,  0],
       [ 5,  2,  1,  3,  0],
       [ 8,  1,  3,  9, 10]], dtype=int32)

In [19]:
padded = pad_sequences(sequences, padding='post', truncating='post', maxlen=5)
padded

array([[4, 2, 1, 3, 0],
       [4, 2, 1, 6, 0],
       [5, 2, 1, 3, 0],
       [7, 5, 8, 1, 3]], dtype=int32)

## <font color='blue'> Training a model to recognize sentiment in text </font>

In [43]:
import json

try:
    with open('Sarcasm_Headlines_Dataset.json','r') as f:
        datastore = json.load(f)

    sentences = []
    labels = []
    urls = []
    for i in datastore:
        sentences.append(i['headline'])
        labels.append(i['is_sarcastic'])
        urls.append(i['article_link'])
except:
    print("JSONDecodeError: Extra data: line 2 column 1 (char 217)")

JSONDecodeError: Extra data: line 2 column 1 (char 217)


In [44]:
import pandas as pd
df = pd.read_json("./Sarcasm_Headlines_Dataset.json", lines=True)
df.head()

article_link  \
0  https://www.huffingtonpost.com/entry/versace-b...   
1  https://www.huffingtonpost.com/entry/roseanne-...   
2  https://local.theonion.com/mom-starting-to-fea...   
3  https://politics.theonion.com/boehner-just-wan...   
4  https://www.huffingtonpost.com/entry/jk-rowlin...   

                                            headline  is_sarcastic  
0  former versace store clerk sues over secret 'b...             0  
1  the 'roseanne' revival catches up to our thorn...             0  
2  mom starting to fear son's web series closest ...             1  
3  boehner just wants wife to listen, not come up...             1  
4  j.k. rowling wishes snape happy birthday in th...             0

In [65]:
sentences = list(df['article_link'])
labels = list(df['is_sarcastic'])
urls = list(df['article_link'])

In [67]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences


tokenizer = Tokenizer(oov_token="<OOV>")
tokenizer.fit_on_texts(sentences)
word_index = tokenizer.word_index

sequences = tokenizer.texts_to_sequences(sentences)
padded = pad_sequences(sequences, padding='post')

print(padded[0])
print(padded.shape)

[    2     4     5     3     6 12731    95  2105     8 12732     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0]
(26709, 46)


In [68]:
training_size = 20000
training_sentences = sentences[0:training_size]
testing_sentences = sentences[training_size:]
training_labels = labels[0:training_size]
testing_labels = labels[training_size:]

In [69]:
vocab_size = 10000
embedding_dim = 16
max_length = 100
trunc_type='post'
padding_type='post'
oov_tok = "<OOV>"
training_size = 20000

In [70]:
tokenizer = Tokenizer(num_words=vocab_size, oov_token=oov_tok)
tokenizer.fit_on_texts(training_sentences)

word_index = tokenizer.word_index

training_sequences = tokenizer.texts_to_sequences(training_sentences)
training_padded = pad_sequences(training_sequences, maxlen=max_length, padding=padding_type, truncating=trunc_type)

testing_sequences = tokenizer.texts_to_sequences(testing_sentences)
testing_padded = pad_sequences(testing_sequences, maxlen=max_length, padding=padding_type, truncating=trunc_type)

print(padded[0])
print(padded.shape)

[    2     4     5     3     6 12731    95  2105     8 12732     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0]
(26709, 46)


In [71]:
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(vocab_size, embedding_dim, input_length=max_length),
    tf.keras.layers.GlobalAveragePooling1D(),
    tf.keras.layers.Dense(24, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [72]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 100, 16)           160000    
_________________________________________________________________
global_average_pooling1d_2 ( (None, 16)                0         
_________________________________________________________________
dense_4 (Dense)              (None, 24)                408       
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 25        
Total params: 160,433
Trainable params: 160,433
Non-trainable params: 0
_________________________________________________________________


In [73]:
import numpy as np
training_padded = np.array(training_padded)
training_labels = np.array(training_labels)
testing_padded = np.array(testing_padded)
testing_labels = np.array(testing_labels)

In [74]:
num_epochs = 5
history = model.fit(training_padded, training_labels, epochs=num_epochs, validation_data=(testing_padded, testing_labels), verbose=2)

Epoch 1/5
625/625 - 1s - loss: 0.4381 - accuracy: 0.8069 - val_loss: 0.0698 - val_accuracy: 0.9999
Epoch 2/5
625/625 - 1s - loss: 0.0224 - accuracy: 1.0000 - val_loss: 0.0070 - val_accuracy: 1.0000
Epoch 3/5
625/625 - 1s - loss: 0.0032 - accuracy: 1.0000 - val_loss: 0.0023 - val_accuracy: 1.0000
Epoch 4/5
625/625 - 1s - loss: 0.0012 - accuracy: 1.0000 - val_loss: 0.0011 - val_accuracy: 1.0000
Epoch 5/5
625/625 - 1s - loss: 5.5410e-04 - accuracy: 1.0000 - val_loss: 6.0505e-04 - val_accuracy: 1.0000


In [75]:
sentence = ["granny starting to fear spiders in the garden might be real", "game of thrones season finale showing this sunday night"]
sequences = tokenizer.texts_to_sequences(sentence)
padded = pad_sequences(sequences, maxlen=max_length, padding=padding_type, truncating=trunc_type)
print(model.predict(padded))

[[0.9967818]
 [0.970959 ]]


## <font color='blue'> 4. Machine Learning with Recurrent Neural Networks </font>