# <font color='orange'> NumPy </font>

In [1]:
import numpy as np

### 1) 배열 객체 (ndarray 객체)

`array() 함수 사용`

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
np.array([1,2,3,4], dtype=np.float)

array([1., 2., 3., 4.])

In [4]:
np.array([range(i, i+3) for i in [1, 4, 7]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

`초기화`

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
np.full((2, 3), 5)

array([[5, 5, 5],
       [5, 5, 5]])

In [11]:
np.ones((1,2))

array([[1., 1.]])

In [12]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

`arange()함수`

In [14]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

`linspace()함수`

In [17]:
np.linspace(0, 100, 3)

array([  0.,  50., 100.])

In [19]:
np.linspace(0, 100, 10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

`logspace()함수`

In [164]:
arr = np.logspace(0, 1, 100, base=10.0)
arr

array([ 1.        ,  1.02353102,  1.04761575,  1.07226722,  1.09749877,
        1.12332403,  1.149757  ,  1.17681195,  1.20450354,  1.23284674,
        1.26185688,  1.29154967,  1.32194115,  1.35304777,  1.38488637,
        1.41747416,  1.45082878,  1.48496826,  1.51991108,  1.55567614,
        1.59228279,  1.62975083,  1.66810054,  1.70735265,  1.7475284 ,
        1.78864953,  1.83073828,  1.87381742,  1.91791026,  1.96304065,
        2.009233  ,  2.05651231,  2.10490414,  2.15443469,  2.20513074,
        2.25701972,  2.3101297 ,  2.36448941,  2.42012826,  2.47707636,
        2.53536449,  2.59502421,  2.65608778,  2.71858824,  2.7825594 ,
        2.84803587,  2.91505306,  2.98364724,  3.05385551,  3.12571585,
        3.19926714,  3.27454916,  3.35160265,  3.43046929,  3.51119173,
        3.59381366,  3.67837977,  3.76493581,  3.85352859,  3.94420606,
        4.03701726,  4.1320124 ,  4.22924287,  4.32876128,  4.43062146,
        4.53487851,  4.64158883,  4.75081016,  4.86260158,  4.97

### 2) 난수

In [20]:
np.random.random((3, 3))

array([[0.87394726, 0.44826231, 0.99058757],
       [0.02997524, 0.85318809, 0.4778993 ],
       [0.16185498, 0.24873658, 0.42981256]])

In [21]:
np.random.randint(0, 10, (3,3))

array([[6, 1, 5],
       [1, 8, 0],
       [2, 7, 5]])

In [22]:
np.random.normal(0, 1, (3,3))

array([[-1.11546004e+00, -1.74387220e+00, -4.34729864e+00],
       [-1.88610580e-01, -6.83786935e-01,  1.13628735e+00],
       [ 2.38342948e-03, -1.10704511e+00,  6.46548592e-01]])

In [23]:
np.random.seed(0)

In [35]:
arr1 = np.random.randint(10, size=6)
arr1

array([8, 1, 5, 9, 8, 9])

In [36]:
arr2 = np.random.randint(10, size=(2, 3))
arr2

array([[4, 3, 0],
       [3, 5, 0]])

### 3) 사이즈

In [32]:
arr1.size

6

In [33]:
arr1.shape

(6,)

In [34]:
arr1.ndim

1

### 4) 인덱싱

- 인덱싱: 단일 요소 접근
- 인덱스를 이용해 새로운 값 할당

In [27]:
arr1 = np.random.randint(10, size=6)

In [28]:
arr1

array([8, 8, 1, 6, 7, 7])

In [29]:
arr1[0]

8

In [30]:
arr1[5]

7

In [31]:
arr1[-1]

7

In [37]:
arr2[0]

array([4, 3, 0])

In [38]:
arr2[1]

array([3, 5, 0])

In [39]:
arr2[-1]

array([3, 5, 0])

In [40]:
arr2[1][0]

3

In [41]:
#arr2[행, 열]

In [44]:
arr2[0][0]

4

In [43]:
arr2[0, 0]

4

In [45]:
arr2[-1, -1]

0

### 4) 슬라이싱

In [47]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
arr1[0:5:1]

array([0, 1, 2, 3, 4])

In [49]:
arr1[:5:1]

array([0, 1, 2, 3, 4])

In [53]:
arr2 = np.arange(12).reshape(-1, 4) #행, 열: -1: 정해지지 않았다 
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [55]:
arr2[:3, :4]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [70]:
arr2[:,-1]

array([ 3,  7, 11])

In [74]:
arr2[:,-1].shape

(3,)

In [80]:
arr2[:,-1]

array([ 3,  7, 11])

In [89]:
arr2[:,:1]

array([[0],
       [4],
       [8]])

In [91]:
arr2[:,0]

array([0, 4, 8])

In [93]:
arr2[:,:1].shape

(3, 1)

In [94]:
arr2[:,0].shape

(3,)

In [97]:
arr2[:,3:]

array([[ 3],
       [ 7],
       [11]])

In [98]:
arr2[:,3:].shape

(3, 1)

In [139]:
arr2[:2, :1]

array([[6],
       [8]])

In [56]:
arr2[:2, :3]

array([[0, 1, 2],
       [4, 5, 6]])

In [58]:
arr2[:2, 2::-1]

array([[2, 1, 0],
       [6, 5, 4]])

In [67]:
arr2[:2, -1]

array([3, 7])

In [68]:
arr2.ndim

2

In [62]:
arr2[np.newaxis]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [99]:
arr2[np.newaxis].shape

(1, 3, 4)

### np.newaxis

### 배열 객체 연결

In [106]:
list1 = [1, 2, 3]
list2 = [4, 5, 6]

In [107]:
np.concatenate([list1, list2])

array([1, 2, 3, 4, 5, 6])

In [115]:
arr1 = np.concatenate([list1, list2], axis=0)

In [116]:
arr2 = arr1.reshape(-1, 3)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [117]:
np.concatenate([arr2, arr2], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [118]:
np.concatenate([arr2, arr2], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

### 3) NumPy 배열 객체의 ufunction(universal function)

In [119]:
np.random.seed(0)

In [120]:
arr2 = np.random.randint(1, 10, (3, 4))
arr2

array([[6, 1, 4, 4],
       [8, 4, 6, 3],
       [5, 8, 7, 9]])

In [121]:
np.sum(arr2)

65

In [122]:
arr2.sum()

65

In [123]:
np.sum(arr2, axis=0)

array([19, 13, 17, 16])

In [124]:
np.sum(arr2, axis=1)

array([15, 21, 29])

In [125]:
np.min(arr2)

1

### 4) 브로드캐스팅

In [126]:
X = np.random.random((10, 3))
X

array([[0.96366276, 0.38344152, 0.79172504],
       [0.52889492, 0.56804456, 0.92559664],
       [0.07103606, 0.0871293 , 0.0202184 ],
       [0.83261985, 0.77815675, 0.87001215],
       [0.97861834, 0.79915856, 0.46147936],
       [0.78052918, 0.11827443, 0.63992102],
       [0.14335329, 0.94466892, 0.52184832],
       [0.41466194, 0.26455561, 0.77423369],
       [0.45615033, 0.56843395, 0.0187898 ],
       [0.6176355 , 0.61209572, 0.616934  ]])

In [128]:
Xmean = X.mean(axis=0)
Xmean

array([0.57871622, 0.51239593, 0.56407584])

In [129]:
X.shape

(10, 3)

In [130]:
Xmean.shape

(3,)

In [131]:
X - Xmean

array([[ 0.38494654, -0.12895441,  0.2276492 ],
       [-0.0498213 ,  0.05564863,  0.3615208 ],
       [-0.50768016, -0.42526663, -0.54385744],
       [ 0.25390363,  0.26576082,  0.30593631],
       [ 0.39990213,  0.28676263, -0.10259648],
       [ 0.20181296, -0.39412151,  0.07584518],
       [-0.43536293,  0.43227298, -0.04222752],
       [-0.16405428, -0.24784032,  0.21015785],
       [-0.12256588,  0.05603802, -0.54528604],
       [ 0.03891928,  0.09969979,  0.05285816]])

### 부울배열과 마스킹 연산

In [134]:
np.random.seed(0)
X = np.random.randint(1, 10, size=(3, 4))
X

array([[6, 1, 4, 4],
       [8, 4, 6, 3],
       [5, 8, 7, 9]])

In [135]:
(X > 5) & (X < 8)

array([[ True, False, False, False],
       [False, False,  True, False],
       [False, False,  True, False]])

부울배열을 이용한 마스킹 연산

In [137]:
np.sum((X > 5) & (X < 8))

3

### 팬시 인덱싱

- 인덱스 배열

In [144]:
X = np.arange(12).reshape((3, 4))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [145]:
row = np.array([0, 1, 2])
col = np.array([1, 2, 3])

In [146]:
X[row]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [147]:
X[col]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [149]:
X = np.zeros(12).reshape((3, 4))
X

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [150]:
X[1, 0] = 1
X

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [152]:
X[1, 0] = 0

In [153]:
X[1, [1, 3]] = 1 #[1, 3]은 팬시 인덱싱 
X

array([[0., 0., 0., 0.],
       [0., 1., 0., 1.],
       [0., 0., 0., 0.]])

In [154]:
X[[0, 2], [1, 3]] = 2
X

array([[0., 2., 0., 0.],
       [0., 1., 0., 1.],
       [0., 0., 0., 2.]])

In [155]:
X[0:3, [0, 2]] = 3
X

array([[3., 2., 3., 0.],
       [3., 1., 3., 1.],
       [3., 0., 3., 2.]])

In [157]:
np.sort(X)

array([[0., 2., 3., 3.],
       [1., 1., 3., 3.],
       [0., 2., 3., 3.]])

# <font color='orange'> Pandas </font>

In [159]:
import pandas as pd

data = pd.Series(np.linspace(0, 1, num=5))
data

0    0.00
1    0.25
2    0.50
3    0.75
4    1.00
dtype: float64

In [161]:
data.values

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [162]:
type(data.values)

numpy.ndarray

In [163]:
data.index

RangeIndex(start=0, stop=5, step=1)