# 파이썬 강의
--------------------
--------------------

 - 일정: 6월8일 ~ 9일
 - 시간: 10시 - 18시 


In [ ]:
- 

In [4]:
print(1)

1


In [1]:
#fdkgdfk
#ddfaljke
print(1)

1


# 강의 실습 환경
-------------------------------
-------------------------------
- Anaconda Python 3.7 Jupyter Notebook

- https://www.anaconda.com/products/individual#download-section


# 목차

-------------------------------
-------------------------------
## Day1 (6/8)

1. Python Introduction 

2. Jupyter Notebook 명령어, 설치

3. 변수와 자료형 (feat 메모리)
      
4. 파일과 파일처리 (feat 하드디스크)

5. 코드구조

6. 함수      
                      

-------------------------------
## Day2 (6/9)

7. 변수와 객체 그리고 클래스 Intro 

8. 클래스와 객체 지향 프로그래밍

11. NumPy

12. Pandas

13. 마무리

# 어제 안한 내용

--------------------------
--------------------------

### <font color='orange'> Q3. 다음 data 문자열을 result의 문자열로 변환 하세요. </font>

입출력 예시

`
input_data = 'Beatiful-is-better-than-agly.' 
output = 'Beatiful Is Better Than Agly.'
`

In [39]:
input_data = "Beatiful-is-better-than-agly."

input_data.split("-")

['Beatiful', 'is', 'better', 'than', 'agly.']

In [40]:
'Beatiful'.upper()

'BEATIFUL'

In [573]:
mylist = input_data.split("-")

k = mylist[0][0].upper() + mylist[0][1:] + " " + mylist[1][0].upper()+mylist[1][1:] + " " + mylist[2][0].upper()+mylist[2][1:] + " " + mylist[3][0].upper()+mylist[3][1:] + " " + mylist[4][0].upper()+mylist[4][1:] + " "

k

'Beatiful Is Better Than Agly. '

### <font color = 'red'> Q3 다른 풀이 - title 함수 </font>

In [44]:
input_data = "Beatiful-is-better-than-agly."
result = input_data.title()

" ".join(result.split('-'))

'Beatiful Is Better Than Agly.'

In [45]:
txt = "Welcome-to-my-world"
x = txt.title()
print(x)

Welcome-To-My-World


In [46]:
txt = "Welcome to my world"
x = txt.title()
print(x)

Welcome To My World


================================================================================================================

### <font color='red'> len()함수를 통해 자료의 크기를 반환해보자 </font>


In [48]:
mydict = {"a": [3.4], "b": 2, "c":0}

len(mydict)

3

In [49]:
myset = {"a","b","c"}
len(myset)

3

In [50]:
mylist = [1,2,3,4,5,6]
len(mylist)

6

In [51]:
mystr = 'hello'
len(mystr)

5

In [52]:
## 숫자 자료형에는 크기가 없다!

a = 10
len(a)

TypeError: object of type 'int' has no len()

In [53]:
## bool자료형에는 크기가 없다.

len(True)

TypeError: object of type 'bool' has no len()

================================================================================================================

### <font color='red'> 파이썬 내장함수 sorted() </font>

https://docs.python.org/3/howto/sorting.html
https://docs.python.org/3/library/functions.html#sorted

- sort()는 리스트의 메소드 이다. 즉 자료형이 리스트인 경우에만 사용할 수 있다. 
- sorted()는 파이썬 내장함수로 인자로 iterable한 객체를 받는다. `sorted(iterable)`
    - sorted()의 반환값은 list이다.

In [55]:
# list에서 sorted와 sort의 차이점.
a = [3,4,1,2,5,6,4,20,33,1,-4,0]
a.sort()
a

[-4, 0, 1, 1, 2, 3, 4, 4, 5, 6, 20, 33]

In [56]:
a = [3,4,1,2,5,6,4,20,33,1,-4,0]
sorted(a)

[-4, 0, 1, 1, 2, 3, 4, 4, 5, 6, 20, 33]

In [57]:
mydict = {'a':30, 'c':100, 'b':1, 'z':1000, 'y':0}


AttributeError: 'dict' object has no attribute 'sort'

In [58]:
# sort()는 리스트 자료형에서만 사용할 수 있는 반면에 sorted함수는 기타 다른 iterable한 객체에도 사용할 수 있다. 

# sorted()의 인자로 dict를 사용하면,
sorted({'a':30, 'c':100, 'b':1, 'z':1000, 'y':0})

['a', 'b', 'c', 'y', 'z']

키값을 정렬하여 list로 반환한다. 

In [59]:
# sorted()의 인자로 문자열을 사용하면, 
sorted('this is my life')

[' ', ' ', ' ', 'e', 'f', 'h', 'i', 'i', 'i', 'l', 'm', 's', 's', 't', 'y']

알파벳 순으로 정렬하여 list로 반환한다. (단, 공백은 가장 우선순위가 높다.)

#### list의 메소드 sort()와 파이썬 내장함수 sorted()를 헷갈리지 말자!
    - sorted()의 반환값이 list이기 때문에 헷갈리기 쉽다. 

### <font color = 'orange'> 복습문제 1 생년월일 데이터를 기록한 데이터가 있습니다. 연장자 순으로 정렬하세요. </font>

birth = ['880203','900211','991103','890713','980811']

In [65]:
birth = ['880203','900211','991103','890713','980811']

result = []
for i in birth:
    j = int(i)
    result.append(j)

In [67]:
#sorted(result)
result.sort()
result

[880203, 890713, 900211, 980811, 991103]

### <font color = orange> 복습 문제2 </font>

- 다음과 같이 점수의 배열이 grade 변수명에 저장되어 있다.
    - grade = ['8.65', '9.12', '8.45', '7.81', '8.05', '7.21', '8.31']


- 코드1. grade변수 명에 저장된 데이터를 result.txt 파일로 저장합니다. 
   - result.txt 파일 예시

    `8.65
     9.12
     8.45
     ...
     ` 

- 코드2. result.txt파일을 읽어 가장 높은 점수를 출력하는 코드를 만드세요. 

In [72]:
## 코드1 - 파일 쓰기

grade = ['8.65', '9.12', '8.45', '7.81', '8.05', '7.21', '8.31']

f = open("result_1.txt","w")

for i in grade:
    data = "{}\n".format(i)
    f.write(data)

In [73]:
f.close()

In [75]:
!pwd

/Users/jooyoungson/Sample/PythonProgramming


In [78]:
## 코드2 - 파일을 읽어 가장 높은 점수를 출력하는 코드를 만드세요. 

f = open("result.txt")

best_score = 0

for line in f:
    if float(line) > best_score:
        best_score = float(line)
f.close()

print("The best score is...{}".format(best_score))

The best score is...9.12


## <font color = 'skyblue'> 7. 변수와 객체 그리고 클래스 Intro </font>
-------------------------
1) 파이썬에서 모든 것은 객체로 이루어져 있다. 

2) 변수의 의미

3) 얕은 복사, 깊은복사
- id()

### 파이썬에서는 모든것이 객체다. 



"Everything in Python is an object, and almost everything has attributes and methods"

- 파이썬에서 모든것은 객체(Object)이다. 그리고 대부분의 객체는 속성(attributes)과 메소드(methods)를 갖는다. 라는 말은 파이썬에서 매우 중요한 말입니다. 

- 이 말은...파이썬에서는 부울, 정수, 실수, 문자열, list, dictionary, 함수, 모듈, 프로그램...등 모든 것이 객체로 이루어져 있다는 뜻입니다. 

아래 링크에 전체 내용이 나와있으니 한번 읽어 보세요. 
https://linux.die.net/diveintopython/html/getting_to_know_python/everything_is_an_object.html

### 변수, 객체 참조

변수란 객체의 이름일 뿐이다. 즉, 객체를 참조하는 것이다.

In [79]:
a = 3
b = 4

In [82]:
id(4)

4396583680

In [83]:
id(b)

4396583680

In [87]:
a = [1,2,3]

In [88]:
b = a

In [89]:
b

[1, 2, 3]

In [90]:
a = [1,2,3,4]
b = a

In [91]:
a.pop()

4

In [92]:
a

[1, 2, 3]

In [93]:
b

[1, 2, 3]

### 얕은복사, 깊은 복사

<img src='./fig/img2.jpg'>

<img src='./fig/img3.jpg'>

In [94]:
a = [1,2,3]
b = a

In [96]:
import copy

d = copy.deepcopy(a)

In [97]:
d

[1, 2, 3]

In [99]:
id(d)

140641722473152

In [100]:
id(b)

140641722427136

In [101]:
id(a)

140641722427136

In [102]:
a.append('aa')

In [103]:
a

[1, 2, 3, 'aa']

In [104]:
b

[1, 2, 3, 'aa']

In [105]:
d

[1, 2, 3]

## <font color = 'skyblue'> 8. 클래스와 객체지향 프로그래밍 </font>
--------------------------

#### 클래스: 파이썬 클래스를 이용해 사용자가 객체를 설계하고 


#### <클래스 문법>

1) 클래스 선언

2) 클래스 사용

3) 클래스의 상태와 동작은 속성과 메소드
- self

4) 생성자 `__init__`

5) 멤버변수와 인스턴스 변수

6) 상속

- 메소드 재정의
- 메소드 오버라이드
- 부모클래스 호출: super()


#### <객체를 사용하는 이유>


In [116]:
class MyCar:
    pass

In [117]:
a = MyCar()

In [111]:
- 네이밍 규칙 (PEP8)
    - 클래스 이름: 카멜 케이스
        - MyCar
        - Car
        - (명사형태)
    - 함수 이름: 스네이크 케이스
        - my_car
        - (동사형태)

In [6]:
# 속성: color, category
# 메소드: drive, accel

class Car:
    color = 'red'
    category = 'sedan'
    
    def drive(self):
        print("driving")
    
    def accel(self, speed_up, current_speed=10):
        self.speed_up = speed_up
        self.current_speed = current_speed + self.speed_up
        print("speed_up", self.speed_up, "driving at", self.current_speed)

In [20]:
class Car:
    manufaturer = "Indo" # 클래스 변수
    def __init__(self, color, category):
        self.color = color # 인스턴스 변수
        self.category = category #인스턴스 변수
    
    def drive(self):
        print("driving")
    
    def accel(self, speed_up, current_speed=10):
        self.speed_up = speed_up
        self.current_speed = current_speed + self.speed_up
        print("speed_up", self.speed_up, "driving at", self.current_speed)

In [40]:
class NewCar(Car):
    manufaturer = "Indo"
    
    def __init__(self, color, category, year):
        super().__init__(color,category)
        self.year = year  
        
#     def __init__(self, color, category, year):
#         self.color = color
#         self.category = category
#         self.year = year
    
    def drive(self):
        print("driving")
    
    def accel(self):
        print("stop!!, valocity limitation!!")

In [41]:
a = Car("white","sedan")
b = NewCar("red",'sports car', 2020)

In [42]:
a.color

'white'

In [43]:
b.color

'red'

In [46]:
a.year

AttributeError: 'Car' object has no attribute 'year'

In [47]:
b.year

2020

In [21]:
class NewCar(Car):
    pass

In [23]:
a = NewCar('white','sedan')

In [26]:
a.manufaturer

'Indo'

In [27]:
# 메소드 추가
class NewCar(Car):
    def fly(self):
        print("flying")

In [30]:
c = NewCar("white",'sedan')

In [32]:
c.drive()

driving


In [33]:
c.fly()

flying


In [34]:
# 메소드 재정의
class NewCar(Car):
    def accel(self):
        print("stop!!, valocity limitation!!")

In [35]:
d = NewCar("white",'sports car')

In [37]:
d.accel()

stop!!, valocity limitation!!


In [13]:
mycar = Car("yellow",'sports car')
yourcar = Car("balck", "sedan")

In [16]:
mycar.category

'sports car'

In [17]:
yourcar.category

'sedan'

In [18]:
mycar.manufaturer

'Indo'

In [19]:
yourcar.manufaturer

'Indo'

In [134]:
mycar.drive()

driving


In [135]:
Car.drive(mycar)

driving


In [122]:
mycar.drive()

driving


In [123]:
mycar.accel(20)

speed_up 20 driving at 30


In [28]:
class car:
    def drive(self):
        print("driving")
    def accel(self, speed_up, current_speed=10):
        self.current_speed = current_speed
        self.speed_up = speed_up
        self.current_speed += self.speed_up
        print("speed up {} driving at{}".format(self.speed_up,  self.current_speed))

In [29]:
a = car()
a.accel(10)

speed up 10 driving at20


In [30]:
a.accel(20)

speed up 20 driving at30


### <font color='orange'> Q1. Account 클래스 설계하기 </font>

(자유 설계)

- 속성값으로 잔액(balance)를 갖는다. 
- 메소드로 입금액(deposit)과 인출(withdraw)를 갖는다.
- 잔액을 조회하는 기능역시 메소드로 구현한다. 

In [48]:
class Account:
    def __init__(self, balance=0):
        self.balance = balance    
    def deposit(self, money):
        self.balance += money
    def withdraw(self, money): # 마이너스 통장. 
        self.balance -= money
    def inquire(self):
        print("잔액은 {}원 입니다.".format(self.balance))

In [57]:
kakao = Account(1000)

In [58]:
kakao.inquire()

잔액은 1000원 입니다.


In [59]:
kakao.deposit(20000)

In [60]:
kakao.inquire()

잔액은 21000원 입니다.


### 복습!

**0. 객체, 변수**

**1. 클래스 선언**

**2. 클래스 사용** 

- "객체의 인스턴스"

**3. 클래스는 동작과 상태를 갖는다.** 

- 상태(State): 속성(Attribute)로 표현, 일명 변수
- 동작(Behavior): Methode로 표현, 일명 함수
    - self

**4. 생성자** `__init__`

**5. 클래스 변수와 인스턴스 변수**

- 클래스에 선언된 속성은 클래스 변수라고 하며 이 클래스에 의해 생성된 모든 객체에 대해 같은 속성(값)을 갖는다.
- 객체가 인스턴스화 될 때마다 새로운 값이 할당되며 서로 다른 객체 간에는 속성(값)을 공유 할 수 없다.

**6. 상속**

- 메소드 추가, 메소드 오버라이드, 부모메소드 호출하기


### <font color = 'orange'> Q2. 중간점검 및 응용문제 </font>

------------------

클래스를 이용한 데이터 처리  응용문제


- 파일명: employeefile.txt
- employeefile.txt 파일을 쥬피터노트북과 같은 경로에 이동합니다.

<img src='./fig/img4.jpg'>

In [61]:
!ls

Concents.md                   Salaries.csv
GUI                           basic_5day
Pandas_Questions.ipynb        contents
Pandas_Questions_Answer.ipynb employeefile.txt
Python4DS.ipynb               fig
Python4DS_1day.ipynb          hello.txt
Python4DS_2Day-Copy1.ipynb    result.txt
Python4DS_2Day.ipynb          result_1.txt


#### main 함수

In [31]:
def main():
    #파일 이름을 입력 받는다
    #파일을 읽기모드로 열어 한줄씩 파일을 읽는다. 
    #파일의 각 행의 데이터 속성을 갖는 인스턴스 객체(사원객체)를 만든다. 
      # 사전에 employee 클래스 설계 필요!
      # 사전에 인스턴스 사원 객체를 만드는 함수 필요!  
    #월급이 가장 높은 사원을 찾는 코드를 구현한다. 
    #결과를 출력한다. 
    pass 

### Q2-1 인스턴스 변수로 name, division, jobgrade, years, basic를 갖는 employee 클래스를 설계하세요. 

In [79]:
#data = ['Ahn TaeHee', 'AI Team', '3', '3', '300']

class Employee:
    def __init__(self, name, division, jobgrade, years, basic):
        self.name = name
        self.division = division
        self.jobgrade = int(jobgrade)
        self.years = int(years)
        self.basic = int(basic)

### Q2-2. 설계한 employee클래스를 갖고 안태희(AhnTaeHee)란 사원의 정보를 인스턴스 객체로 만들어 보세요

In [68]:
e1 = Employee('Ahan TaeHee','AI Team', '3', '3', '300')

In [71]:
e1.jobgrade

3

### Q2-3. Employee 클래스에 의해 만들어지는 인스턴스 객체를 자동으로 만드는 함수를 코딩해 보세요. 함수 이름은 `make_employee`입니다.


In [114]:
def make_employee(inputdata):
    name, division, jobgrade, year, basic = inputdata.split(',')
    return Employee(name, division, jobgrade, year, basic)

In [83]:
f = open("employeefile.txt")

for i in f:
    e = make_employee(i)
    
f.close()

In [72]:
def make_employee(inputdata):
    name, division, jopgrade, year, basic = inputdata.split(',')
    return Employee(name, division, jopgrade, year, basic)

In [ ]:
for i in inputdata:
    e = make_employee(i)

### 클래스 정보 접근 메소드

In [85]:
class Employee:
    def __init__(self, name, division, jobgrade, years, basic):
        self.name = name
        self.division = division
        self.jobgrade = int(jobgrade)
        self.years = int(years)
        self.basic = int(basic)

    def get_name(self):
        return self.name
    def get_divison(self):
        return self.division
    def get_jobgrade(self):
        return self.jobgrade
    def get_years(self):
        return self.years
    def get_basic(self):
        return self.basic

### Q2-4. 급여를 계산하는 함수를 코딩하세요.

- 급여는 Basic Salary에 Basic Salary의 10% 곱하기 근속년수를 더한 값. 
- 급여는 Basic Salary + years*BasicSalary * 0.1  공식.

In [122]:
class Employee:
    def __init__(self, name, division, jobgrade, years, basic):
        self.name = name
        self.division = division
        self.jobgrade = int(jobgrade)
        self.years = int(years)
        self.basic = int(basic)
    
    def salary(self):
        self.salary = self.basic + (self.years*self.basic*0.1)
        return self.salary

### Q2-5. 파일을 읽어와서 Employee클래스 인스턴스 객체를 만드는 코드를 구현해 보세요. 


In [123]:
f = open("employeefile.txt")

for line in f:
    e = make_employee(line)
    print(e.salary())

390.0
1020.0
490.0
416.0
220.0


### 전체 코드

In [142]:
class Employee:
    def __init__(self, name, division, jobgrade, years, basic):
        self.name = name
        self.division = division
        self.jobgrade = int(jobgrade)
        self.years = int(years)
        self.basic = int(basic)

    def get_name(self):
        return self.name
    def get_divison(self):
        return self.division
    def get_jobgrade(self):
        return self.jobgrade
    def get_years(self):
        return self.years
    def get_basic(self):
        return self.basic
    
    def salary(self):
        self.salary = self.basic + (self.years*self.basic*0.1)
        return self.salary
    
def make_employee(inputdata):
    name, division, jopgrade, year, basic = inputdata.split(',')
    return Employee(name, division, jopgrade, year, basic)

def main():
    f = open("employeefile.txt")
    best = make_employee(f.readline())
    best_salary = best.salary()
    for line in f:
        e = make_employee(line)
        if e.salary() > best_salary:
            best = e
    f.close()
    print("월급이 가장 높은 사원의 이름은? {} 입니다.".format(best.get_name()))

In [143]:
main()

월급이 가장 높은 사원의 이름은? ParkYoungA 입니다.


In [144]:
class Employee:
    def __init__(self, name, division, jobgrade, years, basic):
        self.name = name
        self.division = division
        self.jobgrade = int(jobgrade)
        self.years = int(years)
        self.basic = int(basic)

    def get_name(self):
        return self.name
    def get_divison(self):
        return self.division
    def get_jobgrade(self):
        return self.jobgrade
    def get_years(self):
        return self.years
    def get_basic(self):
        return self.basic
    
    def salary(self):
        self.salary = self.basic + (self.years*self.basic*0.1)
        return self.salary
    
def make_employee(inputdata):
    name, division, jopgrade, year, basic = inputdata.split(',')
    return Employee(name, division, jopgrade, year, basic)

def main():
    inputfile = open('employeefile.txt')
    best = make_employee(inputfile.readline())
    best_salary = best.salary()
    for line in inputfile:
        e = make_employee(line)
        if e.salary() > best.salary:
            best = e
    inputfile.close()
    print("월급이 가장 높은 사원의 이름은 {}".format(best.get_name()))

In [145]:
main()

월급이 가장 높은 사원의 이름은 KimYoungJae


In [99]:
!ls

Concents.md                   Salaries.csv
GUI                           basic_5day
Pandas_Questions.ipynb        contents
Pandas_Questions_Answer.ipynb employeefile.txt
Python4DS.ipynb               fig
Python4DS_1day.ipynb          hello.txt
Python4DS_2Day-Copy1.ipynb    result.txt
Python4DS_2Day.ipynb          result_1.txt


In [111]:
f = open('employeefile.txt')
for line in f:
    e = make_employee(line)
    print(e.salary)

0
0
0
0
0


In [94]:
class Employee:
    def salary(self):
        return self.basic + (self.basic * self.years * 0.1)

### Q2-6 전체 코드

In [98]:
class Employee:
    def __init__ (self, name, division, jobgrade, years, basic):
        self.name = name
        self.division = division
        self.jobgrade = int(jobgrade)
        self.years = int(years)
        self.basic = float(basic)
        self.salary = 0

    def get_name(self):
        return self.name
    def get_divison(self):
        return self.division
    def get_jobgrade(self):
        return self.jobgrade
    def get_years(self):
        return self.years
    def get_basic(self):
        return self.basic

    def salary(self):
        return self.basic + (self.basic * self.years * 0.1)

def make_employee(inputdata):
    name, division, jobgrade, year, basic = inputdata.split(',')
    return Employee(name, division, jobgrade, year, basic)

def main():
    inputfile = open('employeefile.txt', 'r')
    best = make_employee(inputfile.readline())
    for line in inputfile:
        e = make_employee(line)
        if e.salary() > best.salary():
            highest = e
    inputfile.close()
    
    print("The Name of highest salary employee is", highest.get_name())
    print("years of services", highest.get_years())
    print("division", highest.get_division())
    print("salay", highest.salary())

if __name__ == '__main__':
    main()

TypeError: 'int' object is not callable

## <font color = 'skyblue'> 9. NumPy </font>
------------------------
1) array 만들기

- arange()
- array([])

2) 크기 (size, shape, dim)

- np.size
- np.shape
- np.ndim

3) type

- a.dtype
- type(a)

4) 빈번한 에러

5)  특수 행렬 : 0행렬, 1행렬, 단위 행렬

- np.zeros([])
- np.ones([])
- np.eye()

6) random

- np.random.randint
- np.random.choice
- np.random.permutation

7) reshape, flatten

- np.reshape()
- np.flatten()

8) slicing

9) 주요 연산

- 행렬연산과 브로드 캐스팅
- np.dot()
- np.transpose()
- np.sum()
- np.sqrt()

### numpy tutorial

In [152]:
import numpy as np

a = np.arange(3, 10, 2)

In [258]:
a = np.arange(1,10)

In [260]:
a *3

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [263]:
a + 10

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [178]:
b = np.array((1,2,3,4), dtype = float)

In [179]:
b.dtype

dtype('float64')

In [154]:
type(a)

numpy.ndarray

In [159]:
a = np.array([1,2,3,4,5,6])
b = np.array([[1,2,3],
             [2,3,4]])

In [160]:
a.size

6

In [161]:
b.size

6

In [162]:
a.shape

(6,)

In [163]:
b.shape

(2, 3)

In [165]:
a.ndim

1

In [166]:
b.ndim

2

In [167]:
mylist = [1,2,3,'a']

In [173]:
a = np.array([1,2,3])
b = np.array([2.1,3.2,3])
c = a + b
c

array([3.1, 5.2, 6. ])

In [174]:
b.dtype

dtype('float64')

In [170]:
type(a)

numpy.ndarray

In [180]:
# 특수행렬: 0행렬, 1행렬, 단위행렬 

In [183]:
z = np.zeros([2,3,3])
o = np.ones([3,3,5])
i = np.eye(5) 

In [184]:
z

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [185]:
o

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [186]:
i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [187]:
o.ndim

3

z.ndim

In [190]:
i.shape

(5, 5)

In [264]:
a = 1,2,3

In [265]:
a

(1, 2, 3)

In [271]:
*a, b = 1,2,3

In [272]:
b

3

### random 

In [198]:
r = np.random.randint(1, 10)
r

4

In [196]:
import random

a = random.randint(1,10)
a

7

In [201]:
np.random.randint(low=1, high=100, size=8).reshape(2,4)

array([[12, 63, 25, 46],
       [16, 78, 94, 55]])

In [208]:
np.random.choice(45, 9)

array([26,  5,  8, 37, 17, 21,  1, 41, 24])

In [215]:
from numpy.random import permutation

np.sort(permutation(46)[:6])

array([ 1,  3, 10, 16, 21, 40])

In [224]:
x = np.array([[2,3,4],[1,1,1],[0,0,0]])
x

array([[2, 3, 4],
       [1, 1, 1],
       [0, 0, 0]])

In [225]:
x.size

9

In [226]:
x.shape

(3, 3)

In [228]:
x.flatten().shape

(9,)

In [221]:
x.reshape(9,1)

array([[2],
       [3],
       [4],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0]])

In [222]:
x.reshape(1,9)

array([[2, 3, 4, 1, 1, 1, 0, 0, 0]])

In [223]:
x.reshape(2,4)

ValueError: cannot reshape array of size 9 into shape (2,4)

In [229]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [234]:
arr[4:]

array([4, 5, 6, 7, 8, 9])

In [235]:
arr[3:8] = 12

In [236]:
arr

array([ 0,  1,  2, 12, 12, 12, 12, 12,  8,  9])

In [238]:
a = np.random.randint(low=1, high=100, size=9).reshape(3,3)

In [242]:
a

array([[ 6, 86, 98],
       [90,  7, 74],
       [43, 56, 21]])

In [239]:
a.ndim

2

In [253]:
a[1]

array([90,  7, 74])

In [251]:
a[1:][2]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [257]:
a[:,:]

array([[ 6, 86, 98],
       [90,  7, 74],
       [43, 56, 21]])

## <font color = 'skyblue'> 10. Pandas </font>
-------------------------
1) series와 dataframe

2) 파일 읽기와 저장

3) EDA 연습!